# Generated by Django 6.0.4 on 2026-04-21 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='face_map',
            new_name='FaceMap',
        ),
    ]
