# Generated by Django 6.0.4 on 2026-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_rename_face_map_facemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facemap',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
